imagePullSecrets:
  - name: mtr-registry-cred
controller:
  image:
    registry: mtr.devops.telekom.de
    image: sca/registry.k8s.io/ingress-nginx/controller
  kind: Deployment
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: ingress-nginx
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
  service:
    # externalTrafficPolicy required to get client IP on OTC
    externalTrafficPolicy: "Local"
    annotations:
      kubernetes.io/elb.id: 7147e28a-ac03-4454-9bc7-d766b2bc1a70
      kubernetes.io/elb.ip: 80.158.50.117
      kubernetes.io/elb.subnet-id: 627ce583-4108-4594-92ec-283b56951032